/**
 * Minimal IANA timezone → ISO-3166 alpha-2 lookup for autodetecting region
 * during onboarding. Intentionally not exhaustive — falls back to 'US'.
 */
export const TIMEZONE_TO_COUNTRY: Record<string, string> = {
  // Europe
  'Europe/Moscow': 'RU',
  'Europe/Saratov': 'RU',
  'Europe/Samara': 'RU',
  'Europe/Kaliningrad': 'RU',
  'Europe/Volgograd': 'RU',
  'Europe/Kiev': 'UA',
  'Europe/Kyiv': 'UA',
  'Europe/Minsk': 'BY',
  'Europe/London': 'GB',
  'Europe/Paris': 'FR',
  'Europe/Berlin': 'DE',
  'Europe/Madrid': 'ES',
  'Europe/Rome': 'IT',
  'Europe/Amsterdam': 'NL',
  'Europe/Warsaw': 'PL',
  'Europe/Prague': 'CZ',
  'Europe/Vienna': 'AT',
  'Europe/Istanbul': 'TR',
  'Europe/Athens': 'GR',
  'Europe/Stockholm': 'SE',
  'Europe/Oslo': 'NO',
  'Europe/Helsinki': 'FI',
  'Europe/Copenhagen': 'DK',
  'Europe/Zurich': 'CH',
  'Europe/Lisbon': 'PT',
  'Europe/Dublin': 'IE',
  'Europe/Brussels': 'BE',
  'Europe/Belgrade': 'RS',
  'Europe/Bucharest': 'RO',
  'Europe/Sofia': 'BG',
  'Europe/Budapest': 'HU',
  'Europe/Zagreb': 'HR',
  'Europe/Ljubljana': 'SI',
  'Europe/Bratislava': 'SK',
  'Europe/Tallinn': 'EE',
  'Europe/Riga': 'LV',
  'Europe/Vilnius': 'LT',
  'Europe/Reykjavik': 'IS',
  'Europe/Chisinau': 'MD',
  // Asia — ex-USSR
  'Asia/Almaty': 'KZ',
  'Asia/Aqtau': 'KZ',
  'Asia/Aqtobe': 'KZ',
  'Asia/Atyrau': 'KZ',
  'Asia/Oral': 'KZ',
  'Asia/Qostanay': 'KZ',
  'Asia/Qyzylorda': 'KZ',
  'Asia/Tashkent': 'UZ',
  'Asia/Bishkek': 'KG',
  'Asia/Dushanbe': 'TJ',
  'Asia/Ashgabat': 'TM',
  'Asia/Baku': 'AZ',
  'Asia/Yerevan': 'AM',
  'Asia/Tbilisi': 'GE',
  // Asia — other
  'Asia/Tokyo': 'JP',
  'Asia/Shanghai': 'CN',
  'Asia/Hong_Kong': 'HK',
  'Asia/Seoul': 'KR',
  'Asia/Singapore': 'SG',
  'Asia/Bangkok': 'TH',
  'Asia/Jakarta': 'ID',
  'Asia/Kuala_Lumpur': 'MY',
  'Asia/Manila': 'PH',
  'Asia/Kolkata': 'IN',
  'Asia/Dubai': 'AE',
  'Asia/Riyadh': 'SA',
  'Asia/Jerusalem': 'IL',
  'Asia/Tehran': 'IR',
  'Asia/Karachi': 'PK',
  'Asia/Dhaka': 'BD',
  'Asia/Colombo': 'LK',
  'Asia/Kathmandu': 'NP',
  'Asia/Yangon': 'MM',
  'Asia/Ho_Chi_Minh': 'VN',
  'Asia/Phnom_Penh': 'KH',
  'Asia/Vientiane': 'LA',
  'Asia/Makassar': 'ID',
  'Asia/Jayapura': 'ID',
  'Asia/Pontianak': 'ID',
  'Asia/Taipei': 'TW',
  'Asia/Qatar': 'QA',
  'Asia/Kuwait': 'KW',
  'Asia/Bahrain': 'BH',
  'Asia/Muscat': 'OM',
  // Americas
  'America/New_York': 'US',
  'America/Los_Angeles': 'US',
  'America/Chicago': 'US',
  'America/Denver': 'US',
  'America/Phoenix': 'US',
  'America/Anchorage': 'US',
  'America/Honolulu': 'US',
  'America/Toronto': 'CA',
  'America/Vancouver': 'CA',
  'America/Mexico_City': 'MX',
  'America/Sao_Paulo': 'BR',
  'America/Buenos_Aires': 'AR',
  'America/Santiago': 'CL',
  'America/Bogota': 'CO',
  'America/Lima': 'PE',
  'America/Caracas': 'VE',
  'America/Guayaquil': 'EC',
  'America/La_Paz': 'BO',
  'America/Asuncion': 'PY',
  'America/Montevideo': 'UY',
  'America/Guatemala': 'GT',
  'America/Costa_Rica': 'CR',
  'America/Panama': 'PA',
  'America/Santo_Domingo': 'DO',
  // Oceania
  'Australia/Sydney': 'AU',
  'Australia/Melbourne': 'AU',
  'Australia/Perth': 'AU',
  'Pacific/Auckland': 'NZ',
  // Africa
  'Africa/Johannesburg': 'ZA',
  'Africa/Cairo': 'EG',
  'Africa/Lagos': 'NG',
  'Africa/Casablanca': 'MA',
  'Africa/Algiers': 'DZ',
  'Africa/Tunis': 'TN',
  'Africa/Nairobi': 'KE',
  'Africa/Accra': 'GH',
  'Africa/Dar_es_Salaam': 'TZ',
  'Africa/Addis_Ababa': 'ET',
};

export const COUNTRY_DEFAULT_CURRENCY: Record<string, string> = {
  US: 'USD',
  CA: 'CAD',
  GB: 'GBP',
  FR: 'EUR',
  DE: 'EUR',
  ES: 'EUR',
  IT: 'EUR',
  NL: 'EUR',
  PT: 'EUR',
  AT: 'EUR',
  GR: 'EUR',
  RU: 'RUB',
  KZ: 'KZT',
  UA: 'UAH',
  BY: 'BYN',
  TR: 'TRY',
  PL: 'PLN',
  CZ: 'CZK',
  SE: 'SEK',
  NO: 'NOK',
  FI: 'EUR',
  DK: 'DKK',
  CH: 'CHF',
  UZ: 'UZS',
  KG: 'KGS',
  TJ: 'TJS',
  TM: 'TMT',
  AZ: 'AZN',
  AM: 'AMD',
  GE: 'GEL',
  JP: 'JPY',
  CN: 'CNY',
  HK: 'HKD',
  KR: 'KRW',
  SG: 'SGD',
  TH: 'THB',
  ID: 'IDR',
  MY: 'MYR',
  PH: 'PHP',
  IN: 'INR',
  AE: 'AED',
  SA: 'SAR',
  IL: 'ILS',
  MX: 'MXN',
  BR: 'BRL',
  AR: 'ARS',
  CL: 'CLP',
  CO: 'COP',
  AU: 'AUD',
  NZ: 'NZD',
  ZA: 'ZAR',
  EG: 'EGP',
  IE: 'EUR',
  BE: 'EUR',
  RS: 'RSD',
  RO: 'RON',
  BG: 'BGN',
  HU: 'HUF',
  HR: 'EUR',
  SI: 'EUR',
  SK: 'EUR',
  EE: 'EUR',
  LV: 'EUR',
  LT: 'EUR',
  IS: 'ISK',
  MD: 'MDL',
  IR: 'IRR',
  PK: 'PKR',
  BD: 'BDT',
  LK: 'LKR',
  NP: 'NPR',
  MM: 'MMK',
  VN: 'VND',
  KH: 'KHR',
  LA: 'LAK',
  TW: 'TWD',
  QA: 'QAR',
  KW: 'KWD',
  BH: 'BHD',
  OM: 'OMR',
  PE: 'PEN',
  VE: 'VES',
  EC: 'USD',
  BO: 'BOB',
  PY: 'PYG',
  UY: 'UYU',
  GT: 'GTQ',
  CR: 'CRC',
  PA: 'USD',
  DO: 'DOP',
  MA: 'MAD',
  DZ: 'DZD',
  TN: 'TND',
  KE: 'KES',
  GH: 'GHS',
  TZ: 'TZS',
  ET: 'ETB',
  NG: 'NGN',
};

export function detectCountryFromTimezone(): string {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return TIMEZONE_TO_COUNTRY[tz] || 'US';
  } catch {
    return 'US';
  }
}

// Strict version: returns null when timezone doesn't unambiguously map
// to a country. Used by onboarding to decide whether currency picker
// can be auto-skipped.
export function detectCountryFromTimezoneStrict(): string | null {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return TIMEZONE_TO_COUNTRY[tz] ?? null;
  } catch {
    return null;
  }
}
