appId: com.goalin.subradar
name: "15 - Settings Currency"
---

# Авторизация через demo аккаунт
- runFlow: ./00_setup_auth.yaml

- tapOn:
    text: "Настройки"
- assertVisible: "Настройки"
- assertNotVisible: "undefined"
