appId: com.goalin.subradar
name: "17 - Settings Notifications"
---

# Авторизация через demo аккаунт
- runFlow: ./00_setup_auth.yaml

- tapOn:
    text: "Настройки"
- assertNotVisible: "undefined"
- assertNotVisible: "Ошибка"
