// Fetch a fresh OTP for review@subradar.ai from the dev API.
// In NODE_ENV=development the API returns the generated code in the
// response body, so we can read it directly and feed each digit into the
// OTP inputs.
//
// Side-effect: this call overwrites whatever code Redis was storing
// (e.g. the one the app just generated by tapping "Send code"). The
// verify endpoint then checks our known code against Redis. Match.

const res = http.post(
  'https://api-dev.subradar.ai/api/v1/auth/otp/send',
  {
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'review@subradar.ai' }),
  },
);

const body = JSON.parse(res.body);
const otp = String(body.code || '').padStart(6, '0');

output.OTP_0 = otp[0];
output.OTP_1 = otp[1];
output.OTP_2 = otp[2];
output.OTP_3 = otp[3];
output.OTP_4 = otp[4];
output.OTP_5 = otp[5];
